name: snapd
version: 0.4.14

description: >
  Provides a client to access snapd, which allows you to manage, search and
  install snaps on a Linux system.

homepage: https://github.com/canonical/snapd.dart

environment:
  sdk: '>=2.17.0 <4.0.0'

platforms:
  linux:

dependencies:
  collection: ^1.15.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  meta: ^1.8.0
  path: ^1.8.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  test: ^1.16.8
  test_cov: ^1.0.1
  ubuntu_lints: ^0.4.0
