name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: Atsumi3/actions-setup-fvm@0.0.3
      - uses: bluefireteam/melos-action@v2
      - run: melos generate
      - run: melos test

  coverage:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: Atsumi3/actions-setup-fvm@0.0.3
      - uses: bluefireteam/melos-action@v2
      - run: melos generate
      - run: sudo apt update && sudo apt install -y lcov
      - run: melos coverage
      - uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
